{% set name = "spacy-curated-transformers" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spacy_curated_transformers-{{ version }}.tar.gz
  sha256: b39ad476a8cb23cc6c566b55b14808f34593c8b7849b26cc4718b71e106e9941

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.9
    - curated-transformers >=0.1.0,<0.2.0
    - curated-tokenizers >=0.0.9,<0.1.0
    - pytorch >=1.12.0

test:
  imports:
    - spacy_curated_transformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/explosion/spacy-curated-transformers
  summary: Curated transformer models for spaCy pipelines
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
